import { mcpServer, z } from '@eliware/mcp-server';
import request from 'supertest';
import { jest, describe, test, expect, beforeEach, afterEach } from '@jest/globals';
describe('public server API',()=>{let app,httpInstance,log; beforeEach(async()=>{log={debug:jest.fn(),warn:jest.fn(),error:jest.fn()};({app,httpInstance}=await mcpServer({log,httpPort:0,auth:{mode:'static',token:'test-token'},toolsDir:new URL('../examples/tools/',import.meta.url).pathname}));}); afterEach(()=>httpInstance?.close());

test('authenticates MCP requests',async()=>{expect((await request(app).post('/mcp').send({foo:'bar'})).status).toBe(401); expect((await request(app).post('/mcp').set('Authorization','Bearer test-token').send({foo:'bar'})).status).toBe(406)});
test('supports custom auth and metadata',async()=>{const r=await mcpServer({log,httpPort:0,auth:{mode:'static',token:'ok'},toolsDir:new URL('../examples/tools/',import.meta.url).pathname,name:'Custom',version:'2',context:{x:1}}); expect(r.mcpServer.options).toEqual({name:'Custom',version:'2'}); expect((await request(r.app).post('/mcp').set('Authorization','Bearer ok').send({foo:'bar'})).status).toBe(406); r.httpInstance.close()});
test('exports zod',()=>expect(z.object({x:z.string()}).safeParse({x:'ok'}).success).toBe(true));
});
import { handleRequestFailure } from '@eliware/mcp-server';
test('supports stateful transport mode',async()=>{const r=await mcpServer({log:{debug:jest.fn(),warn:jest.fn(),error:jest.fn()},httpPort:0,auth:{mode:'static',token:'test-token'},toolsDir:new URL('../examples/tools/',import.meta.url).pathname,stateless:false}); expect(r.transport).toBeTruthy(); r.httpInstance.close()});
test('handles request failures',()=>{const log={error:jest.fn()}; const res={headersSent:false,status:jest.fn().mockReturnThis(),json:jest.fn()}; handleRequestFailure({log,res},new Error('boom')); expect(log.error).toHaveBeenCalled(); expect(res.status).toHaveBeenCalledWith(500)});
test('handles failures without stack and avoids duplicate response',()=>{const log={error:jest.fn()}; const res={headersSent:true,status:jest.fn(),json:jest.fn()}; handleRequestFailure({log,res},{message:'boom'}); expect(log.error).toHaveBeenCalled(); expect(res.status).not.toHaveBeenCalled()});

test('supports default logger and options',async()=>{const r=await mcpServer({httpPort:0,auth:{mode:'static',token:'test-token'},toolsDir:new URL('../examples/tools/',import.meta.url).pathname}); expect(r.app).toBeTruthy(); r.httpInstance.close()});
test('supports omitted options object',async()=>{const r=await mcpServer({toolsDir:new URL('../examples/tools/',import.meta.url).pathname}); expect(r.app).toBeTruthy(); r.httpInstance.close()});
import { requestEndpoint, listeningCallback } from '@eliware/mcp-server';
test('endpoint callbacks are directly testable',async()=>{const res={status:jest.fn().mockReturnThis(),send:jest.fn()};  const handle=jest.fn().mockResolvedValue(undefined); await requestEndpoint({handle,log:{error:jest.fn()}},{},res); expect(handle).toHaveBeenCalled();});
test('listening callback logs',()=>{const log={debug:jest.fn()}; listeningCallback({log},1234); expect(log.debug).toHaveBeenCalledWith(expect.stringContaining('1234'));});
import { createPostHandler, createListeningHandler } from '@eliware/mcp-server';
test('covers route callback factories',async()=>{const handle=jest.fn().mockRejectedValue(new Error('fail')); const log={error:jest.fn(),debug:jest.fn()}; const res={headersSent:false,status:jest.fn().mockReturnThis(),json:jest.fn()}; await createPostHandler({handle,log})({},res); expect(res.status).toHaveBeenCalledWith(500); createListeningHandler({log,port:7})(); expect(log.debug).toHaveBeenCalled();});
test('supports stdio transport mode',async()=>{const r=await mcpServer({stdio:true,log:{debug:jest.fn(),warn:jest.fn(),error:jest.fn()},toolsDir:new URL('../examples/tools/',import.meta.url).pathname}); expect(r.app).toBeUndefined(); expect(r.httpInstance).toBeUndefined(); expect(r.transport).toBeTruthy(); await r.transport.close();});
test('resolves entrypoint-relative tools and stderr stdio logging',async()=>{const original=process.argv[1]; process.argv[1]='server.mjs'; const r=await mcpServer({stdio:true,entrypoint:'server.mjs',toolsDir:new URL('../examples/tools/',import.meta.url).pathname}); expect(r.transport).toBeTruthy(); await r.transport.close(); process.argv[1]=original;});
test('defaults tools directory beside entrypoint',async()=>{const r=await mcpServer({stdio:true,entrypoint:new URL('../examples/basic.mjs',import.meta.url).pathname}); expect(r.transport).toBeTruthy(); await r.transport.close();});
test('stderr logger writes all levels to stderr',async()=>{const spy=jest.spyOn(console,'error').mockImplementation(()=>{}); const {stderrLogger}=await import('@eliware/mcp-server'); for(const level of ['debug','info','warn','error']) stderrLogger[level]('message'); expect(spy).toHaveBeenCalledTimes(4); spy.mockRestore();});

test('creates HTTP redirect app',async()=>{let middleware; const app={use:jest.fn(fn=>{middleware=fn})}; const createApp=jest.fn(()=>app); const {createRedirectApp}=await import('@eliware/mcp-server'); expect(createRedirectApp({createApp,httpsPort:443})).toBe(app); const res={redirect:jest.fn()}; middleware({headers:{host:'example.test:80'},originalUrl:'/mcp'},res); expect(res.redirect).toHaveBeenCalledWith(301,'https://example.test/mcp');});

test('supports HTTPS-only and validates TLS',async()=>{await expect(mcpServer({httpsPort:443,toolsDir:new URL('../examples/tools/',import.meta.url).pathname,log:{debug:jest.fn(),warn:jest.fn(),error:jest.fn()}})).rejects.toThrow('httpsPort requires tls.key and tls.cert'); const server={listen:jest.fn(),close:jest.fn()}; const r=await mcpServer({httpPort:null,httpsPort:0,tls:{key:'key',cert:'cert'},toolsDir:new URL('../examples/tools/',import.meta.url).pathname,log:{debug:jest.fn(),warn:jest.fn(),error:jest.fn()},createHttpsServer:jest.fn(()=>server)}); expect(r.httpInstance).toBeUndefined(); expect(r.httpsInstance).toBe(server); expect(server.listen).toHaveBeenCalled();});

test('supports both listeners with HTTP redirect',async()=>{const server={listen:jest.fn(),close:jest.fn()}; const createHttpServer=jest.fn(()=>server); const createHttpsServer=jest.fn(()=>server); const r=await mcpServer({httpPort:0,httpsPort:0,httpRedirect:true,tls:{key:'key',cert:'cert'},toolsDir:new URL('../examples/tools/',import.meta.url).pathname,log:{debug:jest.fn(),warn:jest.fn(),error:jest.fn()},createHttpServer,createHttpsServer}); expect(createHttpServer).toHaveBeenCalled(); expect(createHttpsServer).toHaveBeenCalled(); expect(r.httpInstance).toBe(server); expect(r.httpsInstance).toBe(server);});
test('redirect app handles alternate HTTPS port and missing host',async()=>{let middleware; const app={use:jest.fn(fn=>{middleware=fn})}; const {createRedirectApp}=await import('@eliware/mcp-server'); createRedirectApp({createApp:()=>app,httpsPort:8443}); const res={redirect:jest.fn()}; middleware({headers:{},url:'/status'},res); expect(res.redirect).toHaveBeenCalledWith(301,'https://localhost:8443/status');});

test('covers OAuth2 metadata and runtime introspection config',async()=>{const r=await mcpServer({httpPort:0,auth:{mode:'oauth2',issuer:'https://auth',resource:'https://app/mcp',scopes:['read'],introspection:{endpoint:'https://auth/introspect'}},toolsDir:new URL('../examples/tools/',import.meta.url).pathname,log:{debug:jest.fn(),warn:jest.fn(),error:jest.fn()}}); expect((await request(r.app).get('/.well-known/oauth-protected-resource/mcp')).status).toBe(200); r.httpInstance.close();});

test('uses package tools fallback when toolsDir is empty',async()=>{const fs=await import('node:fs'); const toolsDir=new URL('../tools/',import.meta.url).pathname; fs.mkdirSync(toolsDir,{recursive:true}); try { const r=await mcpServer({toolsDir:'',entrypoint:undefined,httpPort:0,auth:{mode:'none'},log:{debug:jest.fn(),warn:jest.fn(),error:jest.fn()}}); expect(r.app).toBeTruthy(); r.httpInstance.close(); } finally { fs.rmSync(toolsDir,{recursive:true,force:true}); }});
test('supports omitted mcpServer options',async()=>{const fs=await import('node:fs'); const toolsDir=new URL('../tools/',import.meta.url).pathname; fs.mkdirSync(toolsDir,{recursive:true}); try { const r=await mcpServer(); expect(r.app).toBeTruthy(); r.httpInstance.close(); } finally { fs.rmSync(toolsDir,{recursive:true,force:true}); }});
