import { jest, test, expect } from '@jest/globals';
import { createOAuthClient } from '../../src/oauth-client.mjs';
const provider={authorization_endpoint:'https://auth/authorize',token_endpoint:'https://auth/token',registration_endpoint:'https://auth/register'};
test('creates PKCE authorization URL and exchanges code',async()=>{const fetchFn=jest.fn().mockResolvedValueOnce({ok:true,json:async()=>provider}).mockResolvedValueOnce({ok:true,json:async()=>({access_token:'x'})}); const client=await createOAuthClient({issuer:'https://auth',client:{mode:'static',clientId:'id'},fetchFn}); const request=client.authorizationUrl({redirectUri:'https://app/cb',scopes:['read'],state:'s',codeVerifier:'verifier'}); expect(request.url).toContain('code_challenge='); expect(await client.exchangeCode({code:'c',redirectUri:'https://app/cb',codeVerifier:request.codeVerifier})).toEqual({access_token:'x'}); expect(fetchFn).toHaveBeenCalledTimes(2);});
test('rejects failed token exchange',async()=>{const fetchFn=jest.fn().mockResolvedValueOnce({ok:true,json:async()=>provider}).mockResolvedValueOnce({ok:false,status:400}); const client=await createOAuthClient({issuer:'https://auth',client:{mode:'static',clientId:'id'},fetchFn}); await expect(client.exchangeCode({code:'c',redirectUri:'x',codeVerifier:'v'})).rejects.toThrow('token exchange');});
test('covers default PKCE values and client_id credential shape',async()=>{const fetchFn=jest.fn().mockResolvedValueOnce({ok:true,json:async()=>provider}); const client=await createOAuthClient({issuer:'https://auth',client:{mode:'static',clientId:'id'},fetchFn}); const request=client.authorizationUrl({redirectUri:'https://app/cb'}); expect(request.codeVerifier).toBeTruthy(); expect(request.url).toContain('scope=');});
test('supports registered client_id credentials',async()=>{const fetchFn=jest.fn().mockResolvedValueOnce({ok:true,json:async()=>provider}); const client=await createOAuthClient({issuer:'https://auth',client:{mode:'dynamic'},store:{load:jest.fn().mockResolvedValue({client_id:'registered'})},fetchFn}); const request=client.authorizationUrl({redirectUri:'https://app/cb',state:'s',codeVerifier:'v'}); expect(request.url).toContain('client_id=registered');});
test('supports omitted authorization options',async()=>{const fetchFn=jest.fn().mockResolvedValueOnce({ok:true,json:async()=>provider}); const client=await createOAuthClient({issuer:'https://auth',client:{mode:'static',clientId:'id'},fetchFn}); const result=client.authorizationUrl(); expect(result.url).toContain('client_id=id'); expect(result.codeVerifier).toBeTruthy();});
test('rejects omitted client options',async()=>{await expect(createOAuthClient()).rejects.toThrow();});
